name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Analyze, and Deploy
    runs-on: self-hosted

    steps:
      # Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

        # Install Java manually
      - name: Install JDK 20
        shell: cmd
        run: |
          curl -L -o jdk-20.zip https://download.java.net/java/GA/jdk20/20/binaries/jdk-20_windows-x64_bin.zip
          unzip jdk-20.zip -d C:\Program Files\Java
          setx JAVA_HOME "C:\Program Files\Java\jdk-20"
          setx PATH "%PATH%;C:\Program Files\Java\jdk-20\bin"

      # Install Maven manually
      - name: Install Maven
        shell: cmd
        run: |
          curl -L -o maven.zip https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.zip
          unzip maven.zip -d C:\Program Files\Apache
          setx MAVEN_HOME "C:\Program Files\Apache\apache-maven-3.8.8"
          setx PATH "%PATH%;C:\Program Files\Apache\apache-maven-3.8.8\bin"

        #      - name: Setup Maven
        #        shell: powershell
        #        run: |
        #          Invoke-WebRequest -Uri "https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.zip" -OutFile "maven.zip"
        #          Expand-Archive -Path "maven.zip" -DestinationPath "$env:USERPROFILE\maven"
        #          echo "MAVEN_HOME=$env:USERPROFILE\maven\apache-maven-3.8.8" >> $env:GITHUB_ENV
        #          echo "$env:USERPROFILE\maven\apache-maven-3.8.8\bin" >> $env:GITHUB_PATH

        #      - name: Install Maven manually for macos runners
        #        run: |
        #          rm -rf $HOME/maven/apache-maven-3.8.8
        #          curl -O https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
        #          tar -xvzf apache-maven-3.8.8-bin.tar.gz
        #          mv apache-maven-3.8.8 $HOME/maven
        #          echo "MAVEN_HOME=$HOME/maven" >> $GITHUB_ENV
        #          echo "$HOME/maven/bin" >> $GITHUB_PATH

        # Build and SonarQube analysis
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn -B verify sonar:sonar -Dsonar.project.settings=./sonar-project.properties
        shell: cmd
#
